Repository zstar1003/ragflow-plus, pull requests merged in 2025-06, with the labels that each got.

#141 增加公式解析块，重构excel文件解析
  management/server/services/knowledgebases/document_parser.py
  management/server/services/knowledgebases/excel_parser.py
Labels: size:L

#143 Dev
  web/src/locales/zh.ts
  web/src/pages/write/index.less
  web/src/pages/write/index.tsx
Labels: size:XXL

#146 feat(write): 优化文档撰写，修复图像不输出的问题
  api/apps/conversation_app.py
  api/db/services/dialog_service.py
  api/db/services/write_service.py
  web/src/hooks/write-hooks.ts
  web/src/pages/write/index.tsx
Labels: size:M

#147 refactor(agent): 移除 deepdoc 相关代码，防止误导deepwiki
  Dockerfile
  agent/component/invoke.py
  api/apps/document_app.py
  api/db/services/task_service.py
  deepdoc/README.md
  deepdoc/README_zh.md
  deepdoc/__init__.py
  deepdoc/parser/__init__.py
  deepdoc/parser/docx_parser.py
  deepdoc/parser/excel_parser.py
  deepdoc/parser/html_parser.py
  deepdoc/parser/json_parser.py
  deepdoc/parser/markdown_parser.py
  deepdoc/parser/pdf_parser.py
  deepdoc/parser/ppt_parser.py
  deepdoc/parser/resume/__init__.py
  deepdoc/parser/resume/entities/__init__.py
  deepdoc/parser/resume/entities/corporations.py
  deepdoc/parser/resume/entities/degrees.py
  deepdoc/parser/resume/entities/industries.py
  deepdoc/parser/resume/entities/regions.py
  deepdoc/parser/resume/entities/res/corp.tks.freq.json
  deepdoc/parser/resume/entities/res/corp_baike_len.csv
  deepdoc/parser/resume/entities/res/corp_tag.json
  deepdoc/parser/resume/entities/res/good_corp.json
  deepdoc/parser/resume/entities/res/good_sch.json
  deepdoc/parser/resume/entities/res/school.rank.csv
  deepdoc/parser/resume/entities/res/schools.csv
  deepdoc/parser/resume/entities/schools.py
  deepdoc/parser/resume/step_one.py
  deepdoc/parser/resume/step_two.py
  deepdoc/parser/txt_parser.py
  deepdoc/parser/utils.py
  deepdoc/vision/__init__.py
  deepdoc/vision/layout_recognizer.py
  deepdoc/vision/ocr.py
  deepdoc/vision/operators.py
  deepdoc/vision/postprocess.py
  deepdoc/vision/recognizer.py
  deepdoc/vision/seeit.py
  deepdoc/vision/t_ocr.py
  deepdoc/vision/t_recognizer.py
  deepdoc/vision/table_structure_recognizer.py
  management/web/types/auto/svg-component-global.d.ts
  management/web/types/auto/svg-component.d.ts
  rag/app/__init__.py
  rag/app/audio.py
  rag/app/book.py
  rag/app/email.py
  rag/app/laws.py
  rag/app/manual.py
  rag/app/naive.py
  rag/app/one.py
  rag/app/paper.py
  rag/app/picture.py
  rag/app/presentation.py
  rag/app/qa.py
  rag/app/resume.py
  rag/app/table.py
  rag/app/tag.py
Labels: size:XXL

#148 feat(file): 支持文件夹上传
  api/db/services/dialog_service.py
  api/db/services/task_service.py
  management/web/src/pages/file/index.vue
  management/web/types/auto/components.d.ts
  pyproject.toml
Labels: size:L

#155 feat(write): 文档撰写模式，支持编辑内容的自动保存和加载
  docker/.env
  web/src/pages/chat/chat-container/index.less
  web/src/pages/write/ai-assistant-config.ts
  web/src/pages/write/index.tsx
Labels: size:L

#157 更新解析excel的函数
  management/server/services/knowledgebases/excel_parser.py
Labels: enhancement, size:S

#160 refactor(knowledgebase): 在批量任务解析中，增加各文件的状态更新
  management/web/src/pages/knowledgebase/index.vue
Labels: size:XS

#162 refactor(api): 优化图片插入的 Markdown 格式，增加最大宽度限制
  api/db/services/dialog_service.py
  api/db/services/write_service.py
Labels: size:XS

#163 feat(write): 在应用模板时增加内容覆盖提示
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/write/index.tsx
Labels: size:L
