Repository zstar1003/ragflow-plus, pull requests merged in 2025-07, with the labels that each got.

#190 优化逻辑与去除冗余代码
  management/server/services/knowledgebases/__init__.py
  management/server/services/knowledgebases/document_parser.py
  management/server/services/knowledgebases/service.py
Labels: enhancement, size:S, lgtm

#201 feat: 增加chunk关联图像修改功能
  api/apps/chunk_app.py
  api/apps/kb_app.py
  web/src/pages/add-knowledge/components/knowledge-chunk/components/image-selector/index.less
  web/src/pages/add-knowledge/components/knowledge-chunk/components/image-selector/index.tsx
  web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx
  web/src/pages/add-knowledge/components/knowledge-images/index.tsx
Labels: size:L

#202 使知识库的embedding可选，修改文档解析时获取embedding的逻辑为从知识库的embd_id获取
  management/server/routes/knowledgebases/routes.py
  management/server/services/knowledgebases/service.py
  management/web/src/common/apis/kbs/knowledgebase.ts
  management/web/src/pages/knowledgebase/index.vue
Labels: enhancement, size:L, lgtm
