Repository zstar1003/ragflow-plus, pull requests merged in 2025-08, with the labels that each got.

#212 fix: 修复后台管理系统中，切换页面后文档勾选记录未保存的问题
  management/web/src/pages/knowledgebase/index.vue
Labels: bug, size:M

#216 docs: 更新版本为v0.5.0
  Dockerfile
  README.md
  README_EN.md
  docker/.env
  docker/nginx/management_nginx.conf
  docs/README.md
  docs/_sidebar.md
  docs/build/README.md
  docs/development/README.md
  docs/skill/README.md
  management/docker-compose.yml
  management/web/src/pages/conversation/index.vue
Labels: size:XXL

#218 修改编码方式和引用提示词细节
  rag/nlp/synonym.py
  rag/nlp/term_weight.py
  rag/prompts.py
Labels: bug, size:XS
